### ISSUE TITLE
how to finish animation based on event?

### ISSUE THREAD

**Issue by hishambakr** [yoruriko/LiquidButton#1]
Thanks for great work. i want to know how to finish animation when i get data from backend? or how to control period of animation?

**Comment by yoruriko** [comment]
It's a static animation at the moment, progress update and finish interface will be added later. Thank you for asking.

**Comment by yoruriko** [comment]
The wave animation can be controller by  ChangeProgress(progress), where the progress is measured in float and 1f = 100%. You will need to turn off the AutoPlay flag to do that. I hope that solve your problem.
