### ISSUE TITLE
Graphical artifact when orientation change

### ISSUE THREAD

**Issue by pepinpin** [yoruriko/LiquidButton#3]
Hi there, 

I'm using your button on a couple of apps, and I can't get around a bug when the orientation is changed... some graphical artifact appear
![device-2016-08-22-155001](https://cloud.githubusercontent.com/assets/8282491/17857192/184579de-6881-11e6-9b79-e28fd5f0adcf.png)

any idea ??

thx in advance ;)

PS : my apps are open source and free with NO ads, hope you're ok that I reuse your work ;)
(check my git for the sources...)

**Comment by yoruriko** [comment]
Sorry about the late reply. I have not considered to include the orientation change when I implement this, as it looks better in portrait and when orientation changes the length and width of the screen change along. The idea was to make it fit for different screen size in portrait, so the radius was calculated based on the width of the device. The other factors like the position of the liquid and wave also affected by this radius value which depends on screen width, therefore it shows  such artifact in landscape.  
Do anything you want with it, It's open sourced. I will try to make it work in landscape later, or you might like to do that and contribute to this widget.
